# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-24 05:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodtaskerapp', '0005_auto_20170418_0842'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='location',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(1, 'Cooking'), (4, 'Delivered'), (3, 'On the way'), (2, 'Ready')]),
        ),
    ]
